export class ShopSettingConstants {
    static PORT = 'PORT'
    static PRODUCTS_SERVICE = 'PRODUCTS_SERVICE'
    static PRODUCTS_CLIENT_PROXY = 'PRODUCTS_CLIENT_PROXY'

    static PRODUCTS_ENTITIES_PATH = 'PRODUCTS_ENTITIES_PATH'
    static PRODUCTS_DATABASE_TYPE = 'PRODUCTS_DATABASE_TYPE'
    static PRODUCT_LOG_LEVEL = 'PRODUCT_LOG_LEVEL'
    static API_GATEWAY_PORT = 'API_GATEWAY_PORT'
    static MASTER_BASE_URL = 'MASTER_BASE_URL'
    static MODE = 'MODE'
    static SHOP_SERVICE = 'SHOP_SERVICE'
}
